Add missing headers for C++23
Add <pthread.h> to resolve errors caused by C++23. C++23 removed
transitive includes so you have to add the necessary C++ headers.

Errors:
packages/modules/Nfc/libnfc-nci/src/nfa/hci/nfa_hci_api.cc:73:3: error:
use of undeclared identifier 'pthread_mutex_lock'; did you mean
'pthread_mutex_t'?
   73 |   pthread_mutex_lock(&nfa_hci_mutex);

packages/modules/Nfc/libnfc-nci/src/nfa/hci/nfa_hci_api.cc:87:5: error:
use of undeclared identifier 'pthread_mutex_unlock'; did you mean
'pthread_mutex_t'?
   87 |     pthread_mutex_unlock(&nfa_hci_mutex);

packages/modules/Nfc/libnfc-nci/src/nfa/hci/nfa_hci_api.cc:91:3: error:
use of undeclared identifier 'pthread_mutex_unlock'; did you mean
'pthread_mutex_t'?
   91 |   pthread_mutex_unlock(&nfa_hci_mutex);

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: presubmit
Change-Id: I984ae8d7388ebc7caedf1f6425465fab1f71a76e